stages:
  - deploy
deploy_dev:
  stage: deploy
  only:
    - master
  tags:
    - php
  script:
  - php C:/Websites/_OSDEV/tsk-terminliste/ci.php
  - xcopy "../TerminLister" "C:\Websites\_OSDEV\tsk-terminliste" /s/h/e/k/f/c/y /EXCLUDE:C:\Websites\excluded.txt
  - cd C:/Websites/_OSDEV/tsk-terminliste
  - composer update
  after_script:
  - phinx migrate
deploy_alpha:
  stage: deploy
  only:
    - release_alpha
  tags:
    - php
  script:
  - php C:/Websites/_OSKUNDE/terminlister/ci.php
  - xcopy "../TerminLister" "C:\Websites\_OSKUNDE\terminlister" /s/h/e/k/f/c/y /EXCLUDE:C:\Websites\excluded.txt
  - cd C:/Websites/_OSKUNDE/terminlister
  - composer update
  after_script:
  - phinx migrate