stages:
  - deploy

deploy_dev:
  stage: deploy
  only:
    - master
  tags:
    - php
  script:
    - php C:/Websites/_OSDEV/terminlister/ci.php
    - xcopy "../TerminLister" "C:\Websites\_OSDEV\tsk-terminlister" /s/h/e/k/f/c/y /EXCLUDE:C:\Websites\excluded.txt
    - cd C:/Websites/_OSDEV/terminlister
    - composer update
    - powershell phinx migrate

deploy_alpha:
  stage: deploy
  only:
    - release_alpha
  tags:
    - php
  script:
    - php C:/Websites/_OSKUNDE/terminlister/ci.php
    - xcopy "../TerminLister" "C:\Websites\_OSKUNDE\tsk-terminlister" /s/h/e/k/f/c/y /EXCLUDE:C:\Websites\excluded.txt
    - cd C:/Websites/_OSKUNDE/terminlister
    - composer update
    - powershell phinx migrate

